        if ( self.detector==2 and (
             self.channel==18 or
             self.channel==19 or
             self.channel==20 or
             self.channel==21 or
             self.channel==22 or
             self.channel==35 or
             self.channel==36 or
             self.channel==37 or
             self.channel==38 or
             self.channel==39 or
             self.channel==40 or
             self.channel==41 or
             self.channel==42 or
             self.channel==43 or
             self.channel==44 or
             self.channel==45 or
             self.channel==46 or
             self.channel==53 or
             self.channel==54 or
             self.channel==55 or
             self.channel==56 or
             self.channel==57 or
             self.channel==58 or
             self.channel==62 or
             self.channel==63 or
             self.channel==64 or
             self.channel==76 or
             self.channel==77 or
             self.channel==78 or
             self.channel==79 or
             self.channel==126 or
             self.channel==127 or
             self.channel==128 or
             self.channel==137 or
             self.channel==138 or
             self.channel==139 or
             self.channel==140 or
             self.channel==141 or
             self.channel==142 or
             self.channel==143 or
             self.channel==144 or
             self.channel==145 or
             self.channel==146 or
             self.channel==147 or
             self.channel==148 or
             self.channel==149 or
             self.channel==150 or
             self.channel==151 or
             self.channel==152 or
             self.channel==162 or
             self.channel==163 or
             self.channel==164 or
             self.channel==165 or
             self.channel==166 or
             self.channel==167 or
             self.channel==168 or
             self.channel==169 or
             self.channel==170 or
             self.channel==187 or
             self.channel==213 or
             self.channel==214 or
             self.channel==215 or
             self.channel==230 or
             self.channel==231 or
             self.channel==233 or
             self.channel==234 or
             self.channel==235 or
             self.channel==236 or
             self.channel==237 or
             self.channel==238 or
             self.channel==247 or
             self.channel==249 or
             self.channel==250 or
             self.channel==251 or
             self.channel==252 or
             self.channel==253 or
             self.channel==254 or
             self.channel==255 or
             self.channel==265 or
             self.channel==266 or
             self.channel==267 or
             self.channel==268 or
             self.channel==269 or
             self.channel==271 or
             self.channel==272 or
             self.channel==281 or
             self.channel==282 or
             self.channel==283 or
             self.channel==284 or
             self.channel==285 or
             self.channel==286 or
             self.channel==287 or
             self.channel==288 or
             self.channel==289 or
             self.channel==298 or
             self.channel==299 or
             self.channel==300 or
             self.channel==301 or
             self.channel==302 or
             self.channel==303 or
             self.channel==304 or
             self.channel==305 or
             self.channel==306 or
             self.channel==315 or
             self.channel==316 or
             self.channel==317 or
             self.channel==318 or
             self.channel==319 or
             self.channel==320 or
             self.channel==321 or
             self.channel==322 or
             self.channel==323 or
             self.channel==332 or
             self.channel==333 or
             self.channel==334 or
             self.channel==335 or
             self.channel==336 or
             self.channel==337 or
             self.channel==338 or
             self.channel==339 or
             self.channel==340 or
             self.channel==349 or
             self.channel==350 or
             self.channel==351 or
             self.channel==352 or
             self.channel==353 or
             self.channel==354 or
             self.channel==355 or
             self.channel==356 or
             self.channel==357 or
             self.channel==366 or
             self.channel==367 or
             self.channel==368 or
             self.channel==369 or
             self.channel==370 or
             self.channel==371 or
             self.channel==372 or
             self.channel==373 or
             self.channel==374 or
             self.channel==383 or
             self.channel==384 or
             self.channel==385 or
             self.channel==386 or
             self.channel==387 or
             self.channel==388 or
             self.channel==389 or
             self.channel==390 or
             self.channel==391 or
             self.channel==404 or
             self.channel==405 or
             self.channel==406 or
             self.channel==407 or
             self.channel==408 or
             self.channel==420 or
             self.channel==421 or
             self.channel==422 or
             self.channel==423 or
             self.channel==427 or
             self.channel==428 or
             self.channel==429 or
             self.channel==430 or
             self.channel==436 or
             self.channel==437 or
             self.channel==438 or
             self.channel==439 or
             self.channel==440 or
             self.channel==441 or
             self.channel==443 or
             self.channel==444 or
             self.channel==445 or
             self.channel==451 or
             self.channel==452 or
             self.channel==453 or
             self.channel==454 or
             self.channel==455 or
             self.channel==464 or
             self.channel==465 or
             self.channel==466 or
             self.channel==467 or
             self.channel==468 or
             self.channel==474 or
             self.channel==475 or
             self.channel==486 or
             self.channel==487 or
             self.channel==488 or
             self.channel==489 or
             self.channel==490 or
             self.channel==511 or
             self.channel==512 or
             self.channel==517 or
             self.channel==518 or
             self.channel==519 or
             self.channel==520 or
             self.channel==521 or
             self.channel==537 or
             self.channel==538 or
             self.channel==539 or
             ) ):